### ISSUE TITLE
Support format 1A8

### ISSUE THREAD

**Issue by jdrake** [apiaryio/dredd#171]
It dropped 11 days ago: https://github.com/apiaryio/api-blueprint/blob/format-1A8/API%20Blueprint%20Specification.md

Would love to see Dredd handle the new Attributes feature!

**Comment by kuba-kubula** [comment]
Hi @jdrake,

I can assure you that Dredd will definitely use Attributes in future. It will take us some time to implement all the MSON + Attributes things, but–hell yeah :bomb: :christmas_tree:

**Comment by jdrake** [comment]
Pummmped :+1:

**Comment by zdne** [comment]
:+1:

**Comment by jdrake** [comment]
:heart:

**Comment by netmilk** [comment]
WIP :muscle:

**Comment by zdne** [comment]
:construction_worker:

**Comment by Almad** [comment]
:joy: :neckbeard:

**Comment by kuba-kubula** [comment]
Will be released soon, fixed at the moment with https://github.com/apiaryio/dredd/pull/179

**Comment by netmilk** [comment]
Just letting know that new Dredd was released right now and it brings support for MSON and Body Attributes description.

**Comment by netmilk** [comment]
This issue should not be closed because Dredd still don't support URI under actions.

**Comment by nevir** [comment]
Optional attributes don't seem to be honored, either:

```md
+ Attributes (object)
    + foo (optional, string)
```
Results in
```json
bodySchema: {
  "type": "object",
  "properties": {
    "id": {"type":"string"}
  },
  "$schema": "http://json-schema.org/draft-04/schema#"
}
```

```
fail: body: At '/foo' Invalid type: null (expected string)
```

**Comment by netmilk** [comment]
API blueprint 1A8 is fully supported since Dredd 0.5.4
