### ISSUE TITLE
Dredd doesn't support array query parameters in Swagger

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/dredd#791]
It's not possible to use the type `array` for query parameters and to use `collectionFormat` in Dredd. Also, per https://github.com/apiaryio/dredd/issues/798, the `x-example` doesn't work well with arrays.

<img width="541" alt="image" src="https://cloud.githubusercontent.com/assets/283441/26401658/3a4531da-4087-11e7-94e6-1103de709557.png">

**Comment by zdne** [comment]
See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameter-object `collectionFormat` for examples of such a swagger document

**Comment by pksunkara** [comment]
No, it is not supported in swagger adapter.

**Comment by frockert** [comment]
+1 
Also hitting this same problem, would be good to see it being supported

**Comment by kylef** [comment]
There are two problems here, the problem with `x-example` not showing up for array parameters is solved by https://github.com/apiaryio/fury-adapter-swagger/pull/106.

The second problem regarding collectionFormat support, https://github.com/apiaryio/fury-adapter-swagger/pull/107 adds support for `csv` and `multi` formats. `ssv`, `tsv`, and `pipes` remain unsupported at the moment.

**Comment by honzajavorek** [comment]
This got fixed and released with https://github.com/apiaryio/dredd-transactions/pull/80.

**Comment by honzajavorek** [comment]
This still doesn't work as expected: https://github.com/apiaryio/fury-adapter-swagger/issues/123 Until there are tests for this feature so we're sure there are no gaps in the implementation, it should be used only experimentally.

**Comment by honzajavorek** [comment]
The issue I linked above is irrelevant (see https://github.com/apiaryio/fury-adapter-swagger/issues/123#issuecomment-324061449), but the experimental status of array URI parameters holds, because the feature is untested on Dredd side. It should probably work as expected, but use it with caution.
